services:
  kurosearch:
    container_name: 'kurosearch'
    restart: on-failure
    image: 'ghcr.io/flurbudurbur/kurosearch:latest'
    ports:
      - '8080:80'
      - '8443:443'
    cap_add:
      - 'NET_ADMIN'
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - '.env'
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - kurosearch:latest
        - kurosearch:1.0.0
        - ghcr.io/flurbudurbur/kurosearch:latest
        - ghcr.io/flurbudurbur/kurosearch:1.0.0

volumes:
  caddy_data:
  caddy_config:
